name: Test

on:
  push:
    branches:
      - "main"
      - "v*.*.*"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "16.0.0"
      - uses: gleam-lang/setup-gleam@v1.0.1
        with:
          gleam-version: "ref:main"
      - run: npm test
      - run: gleam format --check src test
